"use client";
import { useEffect, useState, type PointerEvent as ReactPointerEvent } from "react";
import NetworkCanvas from "@/components/NetworkCanvas";
import HeroScene from "@/components/HeroScene";
import CyberCursor from "@/components/CyberCursor";
import { ArrowDown, ArrowUpRight, Shield, Github, Linkedin, Mail, MapPin, Terminal, X, Menu, LockKeyhole } from "lucide-react";
import type { PortfolioData } from "@/lib/portfolio";
const nav = ["home", "about", "experience", "projects", "skills", "credentials", "field-notes", "contact"];
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
function cardPoint(e: ReactPointerEvent<HTMLElement>) { if(e.pointerType!=="mouse")return; const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height; e.currentTarget.style.setProperty("--spot-x",(x*100)+"%"); e.currentTarget.style.setProperty("--spot-y",(y*100)+"%"); e.currentTarget.style.transform="perspective(900px) rotateX("+((0.5-y)*6)+"deg) rotateY("+((x-0.5)*8)+"deg) translateY(-5px)"; } function cardLeave(e: ReactPointerEvent<HTMLElement>) { e.currentTarget.style.transform=""; }
export default function PortfolioView({ data }: { data: PortfolioData }) {
  const [role, setRole] = useState(0), [active, setActive] = useState("home"), [menu, setMenu] = useState(false), [terminal, setTerminal] = useState(false), [command, setCommand] = useState(""), [answer, setAnswer] = useState("Type help to explore this portfolio."), [sent, setSent] = useState(false), [error, setError] = useState("");
  useEffect(() => { const t = setInterval(() => setRole(v => (v + 1) % data.settings.heroRoles.length), 2800); const obs = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && setActive(e.target.id)), { rootMargin: "-35% 0px -55% 0px" }); nav.forEach(n => { const el = document.getElementById(n); if (el) obs.observe(el); }); return () => { clearInterval(t); obs.disconnect(); }; }, [data.settings.heroRoles.length]);
  const run = (e: React.FormEvent) => { e.preventDefault(); const c = command.toLowerCase().trim(); const lookup: Record<string,string> = { help: "Commands: about · skills · projects · experience · contact · clear", about: data.profile.longBio, skills: data.skills.map(g => `${g.category}: ${g.items.join(", ")}`).join("\n"), projects: data.projects.map(p => `• ${p.title} — ${p.status}`).join("\n"), experience: data.experience.map(x => `${x.role} · ${x.company} (${x.dates})`).join("\n"), contact: data.profile.email, clear: "" }; setAnswer(lookup[c] ?? "Command not found. Type help for available commands."); setCommand(""); };
  async function contact(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); const form = new FormData(e.currentTarget); const r = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), message: form.get("message"), website: form.get("website") }) }); if (r.ok) setSent(true); else setError((await r.json()).error || "Message could not be sent."); }
  return <>
    <CyberCursor/>
    <div className="topline"><span><i className="live-dot"/> PERSONAL PORTFOLIO INTERFACE</span><span>DESIGNATION <b>CS / CYBERSECURITY</b></span><span className="topright"><MapPin size={12}/> {data.profile.location}</span></div>
    <header className="navbar"><a className="brand" href="#home"><span className="brand-mark"><Shield size={19}/></span><span>RS<span className="accent">.</span></span></a><nav>{nav.map(n => <a key={n} className={active === n ? "active" : ""} href={`#${n}`}>{n.replace("field-notes", "field notes")}</a>)}</nav><button className="nav-menu" aria-label="Toggle navigation" onClick={() => setMenu(!menu)}><Menu/></button><a className="console-link" href="/login"><LockKeyhole size={14}/> <span>SECURE ACCESS</span></a></header>{menu && <div className="mobile-nav">{nav.map(n => <a key={n} onClick={() => setMenu(false)} href={`#${n}`}>{n.replace("field-notes", "field notes")}</a>)}</div>}
    <main id="home">
      <section className="hero"><NetworkCanvas/><div className="hero-glow"/><div className="hero-content"><div className="eyebrow"><span className="eyebrow-line"/> SECURITY RESEARCHER <span className="slash">//</span> CYBERSECURITY ENGINEER</div><p className="hero-index">INDEPENDENT THINKING · SECURE BY DESIGN</p><h1>RAVEENA<br/><span>SHARMA</span></h1><div className="roleline"><span className="role-caret"/> {data.settings.heroRoles[role]}</div><p className="hero-quote">{data.settings.heroStatement}</p><div className="hero-actions"><a className="button primary" href="#projects">EXPLORE MY WORK <ArrowUpRight size={16}/></a><a className="button secondary" href={data.profile.resume} target="_blank" rel="noreferrer">DOWNLOAD RESUME <ArrowDown size={15}/></a></div><div className="socials"><a href={data.profile.github} aria-label="GitHub"><Github/></a><a href={data.profile.linkedin} aria-label="LinkedIn"><Linkedin/></a><a href={`mailto:${data.profile.email}`} aria-label="Email"><Mail/></a>{data.profile.tryhackme && <a href={data.profile.tryhackme} aria-label="TryHackMe" className="thm">THM</a>}<span className="social-line"/><span className="social-caption">PUNE, INDIA · OPEN TO BUILD</span></div></div><HeroScene/><div className="hero-footer"><span>PORTFOLIO / 2026</span><span>SCROLL TO EXPLORE <ArrowDown size={12}/></span><span>LAT 18.5204° N · LON 73.8567° E</span></div></section>
      <div className="ticker"><span>SECURE SYSTEMS</span><b>✳</b><span>HUMAN-CENTERED SECURITY</span><b>✳</b><span>RESEARCH → ENGINEERING</span><b>✳</b><span>SECURE SYSTEMS</span></div>
      <section className="section about-section" id="about"><div className="section-tag">01 / PROFILE</div><div className="section-heading"><div><p className="kicker">A LITTLE ABOUT ME</p><h2>Curiosity is my<br/><em>attack surface.</em></h2></div><p className="section-intro">{data.about.introduction}</p></div><div className="about-grid"><div className="identity-card"><div className="card-corners"/><div className="id-top"><span>IDENTITY / CARD</span><Shield size={18}/></div><div className="avatar-mark">{data.profile.portrait ? <img src={data.profile.portrait} alt=""/> : "RS"}<span className="avatar-orbit"/></div><h3>{data.profile.name}</h3><p>{data.profile.title}</p><div className="id-bottom"><span><i className="live-dot"/> AVAILABLE FOR OPPORTUNITIES</span><span>INDIA / IN</span></div></div><div className="about-copy"><p>{data.profile.longBio}</p><div className="metric-grid"><div className="metric"><b>9.0</b><span>CGPA / 10</span></div><div className="metric"><b>6</b><span>SECURITY RESEARCH PROJECTS LED</span></div><div className="metric"><b>TOP 10%</b><span>TRYHACKME GLOBAL RANK</span></div></div><div className="interest-list">{data.about.interests.map(x => <span key={x}>{x}</span>)}</div></div></div></section>
      <section className="section timeline-section" id="experience"><div className="section-tag">02 / FIELD EXPERIENCE</div><div className="section-heading"><div><p className="kicker">FIELD EXPERIENCE</p><h2>Where I’ve<br/><em>made impact.</em></h2></div><p className="section-intro">Research leadership, hands-on engineering and a growing foundation across AI and cloud.</p></div><div className="timeline">{data.experience.map((x,i) => <article className="timeline-item" key={x.company}><div className="timeline-rail"><span>{String(i+1).padStart(2,"0")}</span><i/></div><div className="timeline-body"><div className="timeline-meta"><span>{x.dates}</span><span>0{i+1} / EXPERIENCE</span></div><h3>{x.role}</h3><h4>{x.company}</h4><ul>{x.description.map(d => <li key={d}>{d}</li>)}</ul></div></article>)}</div><div className="education-strip"><div><p className="kicker">EDUCATION</p><h3>{data.education[0]?.degree}</h3><p>{data.education[0]?.institution}</p></div><span>{data.education[0]?.dates}</span><b>{data.education[0]?.score}</b></div></section>
      <section className="section projects-section" id="projects"><div className="section-tag">03 / SELECTED WORK</div><div className="section-heading"><div><p className="kicker">SELECTED WORK</p><h2>Built to solve<br/><em>real problems.</em></h2></div><p className="section-intro">Research becomes meaningful when it meets a system someone can use. Explore what I’m building.</p></div><div className="project-grid">{data.projects.map((p,i) => <article className={`project-card ${p.featured ? "featured" : ""}`} key={p.title} onPointerMove={cardPoint} onPointerLeave={cardLeave}><div className="project-visual"><div className="visual-grid"/><span className="project-no">0{i+1}</span><span className="project-orbit"/><span className="project-glyph">{["◈","⌬","⌁","▣","⟁","◫"][i%6]}</span><span className="project-status"><i className="live-dot"/> {p.status}</span></div><div className="project-info"><div className="project-kicker">{p.category} <span>·</span> {p.year}</div><h3>{p.title}</h3><p className="project-subtitle">{p.subtitle}</p><p className="project-desc">{p.description}</p><div className="tech-tags">{p.technologies.map(t => <span key={t}>{t}</span>)}</div><div className="project-links"><a href={`/projects/${slug(p.title)}`}>PROJECT BRIEF <ArrowUpRight size={14}/></a>{p.github && <a href={p.github} target="_blank" rel="noreferrer">GITHUB <Github size={13}/></a>}</div></div></article>)}</div></section>
      <section className="section skills-section" id="skills"><div className="section-tag">04 / CAPABILITIES</div><div className="section-heading"><div><p className="kicker">CAPABILITIES</p><h2>A map of my<br/><em>toolkit.</em></h2></div><p className="section-intro">From finding the weak link to building a better system. Grounded in fundamentals, driven by curiosity.</p></div><div className="skills-layout"><div className="skills-core"><div className="skill-rings"><div className="skill-center"><Shield size={26}/><b>RS</b><small>CORE</small></div>{["VAPT","PYTHON","CLOUD","DLP","FORENSICS","CRYPTO"].map((x,i)=><span className={`skill-node sn-${i}`} key={x}>{x}</span>)}</div><p>CONNECTED BY CURIOSITY</p></div><div className="skill-categories">{data.skills.map((g,i)=><div className="skill-group" key={g.category}><div className="skill-group-title"><span>0{i+1}</span><h3>{g.category}</h3><span className="group-count">{String(g.items.length).padStart(2,"0")} NODES</span></div><div className="skill-pills">{g.items.map(s=><span key={s}>{s}</span>)}</div></div>)}</div></div></section>
      <section className="section credentials-section" id="credentials"><div className="section-tag">05 / VERIFIED LEARNING</div><div className="section-heading"><div><p className="kicker">VERIFIED LEARNING</p><h2>Credentials &<br/><em>milestones.</em></h2></div><p className="section-intro">Learning is a practice. Here are some of the certifications, roles and milestones that mark the journey.</p></div><div className="credential-grid">{data.certifications.map((c,i)=><article className="credential-card" key={c.name}><div className="credential-top"><span>VERIFIED LEARNING / 0{i+1}</span><Shield size={18}/></div><div className="credential-seal">✳</div><h3>{c.name}</h3><p>{c.issuer}</p><span className={`credential-status ${c.status ? "pending" : ""}`}>{c.status || "COMPLETED"}</span></article>)}</div><div className="achievement-grid">{data.achievements.map(a=><div className="achievement" key={a.title}><span>{a.category}</span><b>{a.title}</b><p>{a.detail}</p></div>)}</div><div className="leadership-row"><p className="kicker">LEADERSHIP / COMMUNITY</p><div>{data.leadership.map(l=><article key={l.role}><span>{l.dates}</span><b>{l.role}</b><p>{l.organization}</p></article>)}</div></div></section>
      <section className="section ctf-section" id="field-notes"><div className="section-tag">06 / COMPETITION LOG</div><div className="section-heading"><div><p className="kicker">COMPETITION LOG</p><h2>Signals from<br/><em>the field.</em></h2></div><p className="section-intro">A small record of competitive security practice. Every round is another chance to learn.</p></div><div className="ctf-board">{data.competitions.map((c,i)=><article className="ctf-row" key={`${c.event}-${i}`}><div className="ctf-medal">{String(i+1).padStart(2,"0")}</div><div className="ctf-event"><span>{c.year} / COMPETITION</span><h3>{c.event}</h3><p>{c.detail}</p></div><div className="ctf-result"><span>RESULT</span><b>{c.result}</b></div><div className="ctf-mark">↗</div></article>)}</div></section>
      <section className="contact-section" id="contact"><div className="contact-orb"/><div className="section-tag">07 / OPEN CHANNEL</div><div className="contact-layout"><div><p className="kicker">OPEN CHANNEL</p><h2>Have a good<br/><em>problem?</em></h2><p className="contact-intro">I’m always interested in thoughtful conversations about security, building things, and where the two meet.</p><a href={`mailto:${data.profile.email}`} className="contact-email">{data.profile.email} <ArrowUpRight size={15}/></a><div className="contact-social"><a href={data.profile.linkedin}>LINKEDIN <ArrowUpRight size={12}/></a><a href={data.profile.github}>GITHUB <ArrowUpRight size={12}/></a></div></div><form className="contact-form" onSubmit={contact}>{sent ? <div className="sent-state"><Shield size={32}/><h3>MESSAGE RECEIVED</h3><p>Thank you for reaching out. I’ll get back to you soon.</p></div> : <><label>YOUR NAME<input required name="name" minLength={2} maxLength={80} placeholder="Name"/></label><label>EMAIL ADDRESS<input required type="email" name="email" maxLength={254} placeholder="you@example.com"/></label><label>YOUR MESSAGE<textarea required name="message" minLength={10} maxLength={3000} rows={4} placeholder="Tell me what you’re working on…"/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>{error && <p className="form-error">{error}</p>}<button className="button primary" type="submit">SEND MESSAGE <ArrowUpRight size={15}/></button></>}</form></div></section>
      <footer><a className="brand" href="#home"><span className="brand-mark"><Shield size={17}/></span><span>RS<span className="accent">.</span></span></a><span>© {new Date().getFullYear()} RAVEENA SHARMA</span><span>BUILT WITH INTENTION · SECURED BY DESIGN</span><button className="terminal-trigger" onClick={()=>setTerminal(true)}><Terminal size={14}/> OPEN TERMINAL</button></footer>
    </main>{terminal && <div className="terminal-shade" onClick={()=>setTerminal(false)}><div className="terminal-window" onClick={e=>e.stopPropagation()}><div className="terminal-head"><span><Terminal size={15}/> PORTFOLIO TERMINAL</span><button onClick={()=>setTerminal(false)} aria-label="Close"><X size={17}/></button></div><div className="terminal-body"><p>RAVEENA_OS // interactive portfolio guide</p><pre>{answer}</pre><form onSubmit={run}><span>visitor@raveena:~$</span><input autoFocus value={command} onChange={e=>setCommand(e.target.value)} aria-label="Terminal command"/></form></div></div></div>}
  </>;
}
